# Language support configuration: https://github.com/helix-editor/helix/blob/master/languages.toml
# See the languages documentation: https://docs.helix-editor.com/master/languages.html
# Air is an R formatter and language server: https://posit-dev.github.io/air/

[language-server]
r = { command = "R", args = ["--no-echo", "-e", "languageserver::run()"] }

[language-server.air]
command = "air"
args = ["language-server"]

[[language]]
name = "r"
scope = "source.r"
injection-regex = "(r|R)"
file-types = [
  "r",
  "R",
  { glob = ".Rprofile" },
  { glob = "Rprofile.site" },
  { glob = ".RHistory" }
]
shebangs = ["r", "R"]
comment-tokens = ["#", "#'"]
indent = { tab-width = 2, unit = "  " }
language-servers = ["air", "r"]
auto-format = true

[[language]]
name = "toml"
auto-format = true
language-servers = ["tombi"]

[[grammar]]
name = "r"
source = { git = "https://github.com/r-lib/tree-sitter-r", rev = "0e6ef7741712c09dc3ee6e81c42e919820cc65ef" }

[[grammar]]
name = "toml"
source = { git = "https://github.com/ikatyang/tree-sitter-toml", rev = "8bd2056818b21860e3d756b5a58c4f6e05fb744e" }
